
import { Language, StudyMode, AppTheme } from './types';

export const UI_TEXT: { [key in Language]: { [key: string]: string } } = {
  [Language.EN]: {
    title: 'StudyMate',
    // ... existing translations ...
    welcome_title: 'Welcome to StudyMate',
    welcome_subtitle: 'Your personal AI-powered study partner.',
    name_label: 'What should we call you?',
    name_placeholder: 'Enter your name',
    age_label: 'How old are you?',
    age_placeholder: 'Enter your age',
    grade_label: 'What grade are you in?',
    grade_placeholder: 'e.g., 10th Grade, University',
    goal_label: 'What\'s your main study goal?',
    goal_placeholder: 'e.g., Ace my history final',
    create_profile_btn: 'Create My Profile',

    nav_home: 'Home',
    nav_sets: 'Sets',
    nav_generator: 'Generator',
    nav_voice: 'Voice',
    nav_profile: 'Profile',

    home_greeting: 'Welcome back',
    home_sets_card_title: 'My Study Sets',
    home_sets_card_subtitle: 'View, edit, and practice your sets.',
    home_generator_card_title: 'AI Study Guide Generator',
    home_generator_card_subtitle: 'Create new study sets from any topic.',
    home_voice_card_title: 'Voice Notes & Essay',
    home_voice_card_subtitle: 'Record audio to generate essays and quizzes.',
    home_stats_card_title: 'My Progress',
    home_stats_card_subtitle: 'Check your stats and achievements.',

    my_study_sets: 'My Study Sets',
    create_new_set: 'Create New Set',
    no_sets_yet: 'You haven\'t created any study sets yet.',
    create_first_set: 'Create Your First Set',
    
    create_set_title: 'Create a New Study Set',
    edit_set_title: 'Edit Study Set',
    set_title_label: 'Title',
    set_title_placeholder: 'e.g., Biology Chapter 5',
    set_description_label: 'Description (optional)',
    set_description_placeholder: 'A brief summary of this set',
    cards_title: 'Flashcards',
    add_card: 'Add Card',
    term_label: 'Term',
    definition_label: 'Definition',
    save_set: 'Save Set',
    import_text: 'Import',
    export_text: 'Export',
    import_modal_title: 'Import Flashcards',
    export_modal_title: 'Export Flashcards',
    paste_text_placeholder: 'Paste your text here (Word, Excel, Google Docs, etc.)',
    separator_label: 'Separate term and definition by:',
    sep_tab: 'Tab',
    sep_comma: 'Comma',
    sep_dash: 'Dash',
    sep_custom: 'Custom',
    custom_sep_placeholder: 'e.g. ;',
    preview_label: 'Preview',
    import_btn: 'Import Cards',
    cancel_btn: 'Cancel',
    copy_text: 'Copy Text',
    copied: 'Copied!',
    close_btn: 'Close',
    no_cards_preview: 'No cards detected. Check your separator.',
    detect_language: 'Detect languages automatically',
    apply_all_term: 'Apply to all terms',
    apply_all_def: 'Apply to all definitions',

    back: 'Back to Sets',
    edit: 'Edit',
    choose_your_mode: 'Choose Your Study Mode',
    mode_flashcards_title: 'Flashcards',
    mode_flashcards_desc: 'Review cards with spaced repetition.',
    mode_test_title: 'Test',
    mode_test_desc: 'Challenge yourself with a practice test.',
    mode_memorise_title: 'Memorise',
    mode_memorise_desc: 'Multi-level mastery learning.',
    mode_cram_title: 'Cram',
    mode_cram_desc: 'Quickly review all cards before an exam.',
    
    generator_title: 'AI Study Guide Generator',
    generator_instructions: 'Enter any topic, and I\'ll create a study guide with key concepts and flashcards for you.',
    topic_placeholder: 'e.g., The French Revolution, Photosynthesis',
    generate_btn: 'Generate',
    loading: 'Generating...',
    key_concepts: 'Key Concepts',
    generated_flashcards: 'Generated Flashcards',
    save_generated_set: 'Save as a New Study Set',

    voice_title: 'Voice to Study',
    voice_instructions: 'Record a lecture, a meeting, or your own notes. AI will transcribe it and create a structured essay.',
    start_recording: 'Start Recording',
    stop_recording: 'Stop Recording',
    upload_audio: 'Upload Audio File',
    processing_audio: 'Listening and writing essay...',
    generating_materials: 'Creating study materials...',
    tab_essay: 'Essay & Summary',
    tab_transcript: 'Transcript',
    create_flashcards: 'Create Flashcards',
    create_quiz: 'Generate Quiz',
    gen_modal_title: 'Generate Study Materials',
    gen_difficulty: 'Difficulty',
    gen_diff_easy: 'Easy',
    gen_diff_medium: 'Medium',
    gen_diff_hard: 'Hard',
    gen_count: 'Number of Items',
    gen_type: 'Material Type',
    gen_type_flashcards: 'Flashcards',
    gen_type_quiz: 'Multiple Choice Quiz',
    gen_btn_create: 'Create',
    
    years_old: 'years old',
    stats_title: 'My Stats',
    study_streak: 'Study Streak',
    days: 'days',
    sets_created: 'Sets Created',
    terms_learned: 'Terms Learned',
    achievements_title: 'Achievements',
    log_out: 'Log Out',
    settings_title: 'Settings',
    
    settings_header: 'Settings',
    section_appearance: 'Appearance',
    section_learning: 'Learning',
    section_account: 'Account',
    
    theme_label: 'Theme',
    theme_blue: 'Classic Blue',
    theme_green: 'Nature Green',
    theme_purple: 'Creative Purple',
    theme_dark: 'Night Mode',
    theme_contrast: 'High Contrast',
    theme_system: 'System Default',
    // New Theme Names
    theme_modern_light: 'Modern Light',
    theme_deep_dark: 'Deep Dark',
    theme_ocean_blue: 'Ocean Blue',
    theme_sunset_warm: 'Sunset Warm',
    theme_cyber_neon: 'Cyber Neon',
    theme_custom: 'Custom Theme',
    customize_theme_btn: 'Customize Theme',
    
    // Customizer
    customizer_title: 'Theme Customizer',
    color_primary: 'Accent Color',
    color_secondary: 'Secondary Color',
    color_bg: 'Background Color',
    color_card: 'Card Background',
    color_text: 'Text Color',
    border_radius: 'Roundness',
    font_style: 'Font Style',
    preview_ui: 'UI Preview',
    save_theme: 'Save Theme',
    reset_theme: 'Reset',
    
    font_size_label: 'Font Size',
    font_small: 'Small',
    font_medium: 'Medium',
    font_large: 'Large',
    reduce_animations: 'Reduce Animations',
    
    flashcard_controls: 'Flashcard Controls',
    tap_to_flip: 'Tap card to flip',
    space_to_flip: 'Spacebar to flip',
    arrow_keys: 'Arrow keys to respond',
    swap_buttons: 'Swap Know/Don\'t Know buttons',
    learning_mode: 'Default Learning Mode',
    mode_standard: 'Standard',
    mode_memorise_all: 'Memorise All',
    
    general_preferences: 'General Preferences',
    test_mode_settings: 'Test Mode Settings',
    memorise_mode_settings: 'Memorise Mode Settings',
    pref_shuffle: 'Shuffle Cards',
    pref_audio_autoplay: 'Audio Autoplay',
    pref_typing_mode: 'Typing Mode',
    pref_notifications: 'Daily Notifications',
    test_behavior: 'Test Behavior',
    test_num_choices: 'Number of Choices',
    test_mastery_threshold: 'Mastery Threshold',
    test_animations: 'Enable Animations',
    test_autosave: 'Auto-Save Progress',
    mem_words_per_level: 'Words per Level',
    mem_mix_types: 'Mix Multiple Choice & Input',
    mem_retry_level1: 'Retry Mistakes after Level 1',
    reset_defaults: 'Reset to Defaults',
    
    flip: 'Flip',
    finish_session: 'Finish Session',
    rate_dont_know: "Don't know",
    rate_know: "Know",
    rate_mastered: "Mastered",
    start_session: 'Start Session',
    session_setup: 'Session Setup',
    select_mode: 'Select Mode',
    mode_standard_desc: 'Go through all cards once.',
    mode_memorise_all_desc: 'Keep going until you master every card.',
    progress_mastered: 'mastered',
    left_to_learn: 'left to learn',
    all_mastered: 'You mastered all cards! 🎉',
    continue_review: 'Continue Reviewing',
    back_to_dashboard: 'Back to Dashboard',

    submit_answer: 'Submit',
    next_question: 'Next Question',
    view_results: 'View Results',
    test_results: 'Test Results',
    your_score: 'Your Score',
    try_again: 'Try Again',
    first_try_score: 'First Try Score',
    questions_remaining: 'Questions remaining',
    question_x_of_y: 'Question {0} of {1}',
    score_label: 'Score',
    exit_save: 'Exit & Save',
    generating_test: 'Generating your smart test...',
    too_few_cards: 'This set has too few cards to generate a test.',
    correct_msg: 'Correct!',
    incorrect_msg: 'Incorrect',
    mastery_progress: 'Mastery Progress',
    streak: 'Streak',
    hint_label: 'Hint',
    progress_saved: 'Progress auto-saved — you can resume later.',

    level_label: 'Level',
    total_progress: 'Total Set Progress',
    level_progress: 'Level Progress',
    mastered_in_level: 'mastered in this level',
    level_complete: 'Level {0} Complete!',
    level_summary_msg: 'You mastered {0} words. {1} words need more practice.',
    continue_next_level: 'Continue to Level {0}',
    memorise_complete: 'Memorise Session Complete!',
    memorise_complete_desc: 'You have mastered every card in this set through all levels.',
    choose_answer: 'Choose an answer',
    type_answer: 'Type your answer',
    definition_label_caps: 'DEFINITION',
    term_label_caps: 'TERM',
    next_level_intro: 'Level {0} includes {1} unmastered words from previous levels and {2} new words.',
    lets_try_again: "Let's try again",
    review_mistakes: 'Review your mistakes',
    mastered_words_list: 'Words you mastered:',
    almost_correct: 'Almost! Correct was: {0}',
    enter_answer: 'Type answer...',
  },
  [Language.NO]: {
    // ... Existing NO translations ...
    title: 'Studievenn',
    welcome_title: 'Velkommen til Studievenn',
    welcome_subtitle: 'Din personlige AI-drevne studiepartner.',
    name_label: 'Hva skal vi kalle deg?',
    name_placeholder: 'Skriv inn navnet ditt',
    age_label: 'Hvor gammel er du?',
    age_placeholder: 'Skriv inn alderen din',
    grade_label: 'Hvilket trinn går du på?',
    grade_placeholder: 'f.eks. 10. klasse, Universitet',
    goal_label: 'Hva er ditt hovedmål med studiene?',
    goal_placeholder: 'f.eks. Få A på historieeksamen',
    create_profile_btn: 'Opprett Min Profil',

    nav_home: 'Hjem',
    nav_sets: 'Sett',
    nav_generator: 'Generator',
    nav_voice: 'Tale',
    nav_profile: 'Profil',

    home_greeting: 'Velkommen tilbake',
    home_sets_card_title: 'Mine Studiesett',
    home_sets_card_subtitle: 'Se, rediger og øv på settene dine.',
    home_generator_card_title: 'AI Studieveiledning-generator',
    home_generator_card_subtitle: 'Lag nye studiesett fra hvilket som helst emne.',
    home_voice_card_title: 'Talenotater & Essay',
    home_voice_card_subtitle: 'Ta opp lyd for å lage essays og quizer.',
    home_stats_card_title: 'Min Fremgang',
    home_stats_card_subtitle: 'Sjekk statistikk og prestasjoner.',

    my_study_sets: 'Mine Studiesett',
    create_new_set: 'Lag Nytt Sett',
    no_sets_yet: 'Du har ikke laget noen studiesett ennå.',
    create_first_set: 'Lag Ditt Første Sett',

    create_set_title: 'Lag et Nytt Studiesett',
    edit_set_title: 'Rediger Studiesett',
    set_title_label: 'Tittel',
    set_title_placeholder: 'f.eks. Biologi Kapittel 5',
    set_description_label: 'Beskrivelse (valgfritt)',
    set_description_placeholder: 'En kort oppsummering av dette settet',
    cards_title: 'Spørrekort',
    add_card: 'Legg til Kort',
    term_label: 'Begrep',
    definition_label: 'Definisjon',
    save_set: 'Lagre Sett',
    import_text: 'Importer',
    export_text: 'Eksporter',
    import_modal_title: 'Importer Spørrekort',
    export_modal_title: 'Eksporter Spørrekort',
    paste_text_placeholder: 'Lim inn teksten din her (Word, Excel, Google Docs, osv.)',
    separator_label: 'Skill begrep og definisjon med:',
    sep_tab: 'Tabulator',
    sep_comma: 'Komma',
    sep_dash: 'Bindestrek',
    sep_custom: 'Egendefinert',
    custom_sep_placeholder: 'f.eks. ;',
    preview_label: 'Forhåndsvisning',
    import_btn: 'Importer Kort',
    cancel_btn: 'Avbryt',
    copy_text: 'Kopier Tekst',
    copied: 'Kopiert!',
    close_btn: 'Lukk',
    no_cards_preview: 'Ingen kort oppdaget. Sjekk skilletegnet ditt.',
    detect_language: 'Oppdag språk automatisk',
    apply_all_term: 'Bruk på alle begreper',
    apply_all_def: 'Bruk på alle definisjoner',

    back: 'Tilbake til Sett',
    edit: 'Rediger',
    choose_your_mode: 'Velg Din Studiemodus',
    mode_flashcards_title: 'Spørrekort',
    mode_flashcards_desc: 'Gå gjennom kortene med repetisjon.',
    mode_test_title: 'Test',
    mode_test_desc: 'Utfordre deg selv med en øvingstest.',
    mode_memorise_title: 'Memorer',
    mode_memorise_desc: 'Mestringslæring over flere nivåer.',
    mode_cram_title: 'Pugg',
    mode_cram_desc: 'Gå raskt gjennom alle kortene før en prøve.',

    generator_title: 'AI Studieveiledning-generator',
    generator_instructions: 'Skriv inn et emne, så lager jeg en studieveiledning med nøkkelbegreper og spørrekort for deg.',
    topic_placeholder: 'f.eks. Den franske revolusjonen, Fotosyntese',
    generate_btn: 'Generer',
    loading: 'Genererer...',
    key_concepts: 'Nøkkelbegreper',
    generated_flashcards: 'Genererte Spørrekort',
    save_generated_set: 'Lagre som et Nytt Studiesett',

    voice_title: 'Tale til Studie',
    voice_instructions: 'Ta opp en forelesning, et møte eller dine egne notater. AI vil transkribere det og lage et strukturert essay.',
    start_recording: 'Start Opptak',
    stop_recording: 'Stopp Opptak',
    upload_audio: 'Last Opp Lydfil',
    processing_audio: 'Lytter og skriver essay...',
    generating_materials: 'Lager studiemateriell...',
    tab_essay: 'Essay & Sammendrag',
    tab_transcript: 'Transkripsjon',
    create_flashcards: 'Lag Spørrekort',
    create_quiz: 'Generer Quiz',
    gen_modal_title: 'Generer Studiemateriell',
    gen_difficulty: 'Vanskelighetsgrad',
    gen_diff_easy: 'Lett',
    gen_diff_medium: 'Medium',
    gen_diff_hard: 'Vanskelig',
    gen_count: 'Antall',
    gen_type: 'Materialtype',
    gen_type_flashcards: 'Spørrekort',
    gen_type_quiz: 'Flervalg Quiz',
    gen_btn_create: 'Opprett',

    years_old: 'år gammel',
    stats_title: 'Min Statistikk',
    study_streak: 'Studie-streak',
    days: 'dager',
    sets_created: 'Sett Laget',
    terms_learned: 'Begreper Lært',
    achievements_title: 'Prestasjoner',
    log_out: 'Logg Ut',
    settings_title: 'Innstillinger',
    
    settings_header: 'Innstillinger',
    section_appearance: 'Utseende',
    section_learning: 'Læring',
    section_account: 'Konto',
    
    theme_label: 'Tema',
    theme_blue: 'Klassisk Blå',
    theme_green: 'Naturgrønn',
    theme_purple: 'Kreativ Lilla',
    theme_dark: 'Nattmodus',
    theme_contrast: 'Høy Kontrast',
    theme_system: 'Systemstandard',
    theme_modern_light: 'Moderne Lys',
    theme_deep_dark: 'Dyp Mørk',
    theme_ocean_blue: 'Havblå',
    theme_sunset_warm: 'Solnedgang',
    theme_cyber_neon: 'Cyber Neon',
    theme_custom: 'Egendefinert',
    customize_theme_btn: 'Tilpass Tema',

    customizer_title: 'Tema-tilpasser',
    color_primary: 'Aksentfarge',
    color_secondary: 'Sekundærfarge',
    color_bg: 'Bakgrunnsfarge',
    color_card: 'Kortbakgrunn',
    color_text: 'Tekstfarge',
    border_radius: 'Runding',
    font_style: 'Skriftstil',
    preview_ui: 'UI Forhåndsvisning',
    save_theme: 'Lagre Tema',
    reset_theme: 'Tilbakestill',
    
    font_size_label: 'Skriftstørrelse',
    font_small: 'Liten',
    font_medium: 'Medium',
    font_large: 'Stor',
    reduce_animations: 'Reduser Animasjoner',

    flashcard_controls: 'Spørrekort-kontroller',
    tap_to_flip: 'Trykk for å snu',
    space_to_flip: 'Mellomrom for å snu',
    arrow_keys: 'Piltaster for å svare',
    swap_buttons: 'Bytt Kan/Kan ikke knapper',
    learning_mode: 'Standard Læringsmodus',
    mode_standard: 'Standard',
    mode_memorise_all: 'Memorer Alt',

    general_preferences: 'Generelle Innstillinger',
    test_mode_settings: 'Testmodus Innstillinger',
    memorise_mode_settings: 'Memorise Modus Innstillinger',
    pref_shuffle: 'Bland Kort',
    pref_audio_autoplay: 'Lyd Autoplay',
    pref_typing_mode: 'Skrivemodus',
    pref_notifications: 'Daglige Varsler',
    test_behavior: 'Testoppførsel',
    test_num_choices: 'Antall Valg',
    test_mastery_threshold: 'Mestringsterskel',
    test_animations: 'Aktiver Animasjoner',
    test_autosave: 'Auto-lagre Fremgang',
    mem_words_per_level: 'Ord per Nivå',
    mem_mix_types: 'Bland Flervalg & Skriving',
    mem_retry_level1: 'Prøv feil på nytt etter Nivå 1',
    reset_defaults: 'Tilbakestill til Standard',

    flip: 'Snu',
    finish_session: 'Avslutt Økt',
    rate_dont_know: "Kan ikke",
    rate_know: "Kan",
    rate_mastered: "Mestret",
    start_session: 'Start Økt',
    session_setup: 'Økt Oppsett',
    select_mode: 'Velg Modus',
    mode_standard_desc: 'Gå gjennom alle kortene én gang.',
    mode_memorise_all_desc: 'Fortsett til du mestrer alle kortene.',
    progress_mastered: 'mestret',
    left_to_learn: 'igjen å lære',
    all_mastered: 'Du mestret alle kortene! 🎉',
    continue_review: 'Fortsett å Øve',
    back_to_dashboard: 'Tilbake til Dashboard',

    submit_answer: 'Svar',
    next_question: 'Neste Spørsmål',
    view_results: 'Se Resultater',
    test_results: 'Testresultater',
    your_score: 'Din Poengsum',
    try_again: 'Prøv Igjen',
    first_try_score: 'Første Forsøk Poengsum',
    questions_remaining: 'Gjenstående spørsmål',
    question_x_of_y: 'Spørsmål {0} av {1}',
    score_label: 'Poeng',
    exit_save: 'Avslutt & Lagre',
    generating_test: 'Genererer din smarte test...',
    too_few_cards: 'Dette settet har for få kort til å generere en test.',
    correct_msg: 'Riktig!',
    incorrect_msg: 'Feil',
    mastery_progress: 'Mestringsfremgang',
    streak: 'Streak',
    hint_label: 'Hint',
    progress_saved: 'Fremgang lagret automatisk — du kan fortsette senere.',

    level_label: 'Nivå',
    total_progress: 'Total Fremgang',
    level_progress: 'Nivå Fremgang',
    mastered_in_level: 'mestret i dette nivået',
    level_complete: 'Nivå {0} Fullført!',
    level_summary_msg: 'Du mestret {0} ord. {1} ord trenger mer øving.',
    continue_next_level: 'Fortsett til Nivå {0}',
    memorise_complete: 'Memorise Økt Fullført!',
    memorise_complete_desc: 'Du har mestret hvert kort i dette settet gjennom alle nivåer.',
    choose_answer: 'Velg et svar',
    type_answer: 'Skriv svaret ditt',
    definition_label_caps: 'DEFINISJON',
    term_label_caps: 'BEGREP',
    next_level_intro: 'Nivå {0} inkluderer {1} ikke-mestret ord fra tidligere nivåer og {2} nye ord.',
    lets_try_again: "La oss prøve igjen",
    review_mistakes: 'Se over feilene dine',
    mastered_words_list: 'Ord du mestret:',
    almost_correct: 'Nesten! Riktig var: {0}',
    enter_answer: 'Skriv svar...',
  },
};

export const STUDY_MODE_DETAILS = {
  [StudyMode.MEMORISE]: {
    titleKey: 'mode_memorise_title',
    descKey: 'mode_memorise_desc',
  },
  [StudyMode.FLASHCARDS]: {
    titleKey: 'mode_flashcards_title',
    descKey: 'mode_flashcards_desc',
  },
  [StudyMode.TEST]: {
    titleKey: 'mode_test_title',
    descKey: 'mode_test_desc',
  },
  [StudyMode.CRAM]: {
    titleKey: 'mode_cram_title',
    descKey: 'mode_cram_desc',
  },
};

// Preset Theme Definitions (for Customizer start points)
export const PRESET_THEMES = {
  [AppTheme.ModernLight]: {
    primaryColor: '#4A90E2',
    secondaryColor: '#A6C8FF',
    backgroundColor: '#FFFFFF',
    cardColor: '#F5F7FA',
    textColor: '#1C1C1E',
    borderRadius: 12,
    fontFamily: 'Inter',
  },
  [AppTheme.DeepDark]: {
    primaryColor: '#00D1FF',
    secondaryColor: '#007A99',
    backgroundColor: '#000000',
    cardColor: '#0F0F10',
    textColor: '#E6E6E6',
    borderRadius: 8,
    fontFamily: 'Inter',
  },
  [AppTheme.OceanBlue]: {
    primaryColor: '#006CBE',
    secondaryColor: '#4AB2FF',
    backgroundColor: '#E6F4FF',
    cardColor: '#F1F9FF',
    textColor: '#0E1A2A',
    borderRadius: 16,
    fontFamily: 'Nunito',
  },
  [AppTheme.SunsetWarm]: {
    primaryColor: '#FF6A3D',
    secondaryColor: '#FF9E6B',
    backgroundColor: '#FFF4E8',
    cardColor: '#FFE9D6',
    textColor: '#4A2B1C',
    borderRadius: 20,
    fontFamily: 'Poppins',
  },
  [AppTheme.CyberNeon]: {
    primaryColor: '#8B00FF',
    secondaryColor: '#00FFEA',
    backgroundColor: '#0A0A0F',
    cardColor: '#13131A',
    textColor: '#F2F2F2',
    borderRadius: 4,
    fontFamily: 'Inter',
  },
  [AppTheme.Blue]: { // Classic
    primaryColor: '#4255ff',
    secondaryColor: '#ffcd1f',
    backgroundColor: '#f6f7fb',
    cardColor: '#ffffff',
    textColor: '#2d3748',
    borderRadius: 12,
    fontFamily: 'Nunito',
  }
};
